name: LearnMMF
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - conda-forge
dependencies:
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2022.12.7
  - colorama=0.4.6
  - cpuonly=2.0
  - cudatoolkit=10.2.89
  - cycler=0.11.0
  - fftw=3.3.9
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - icc_rt=2022.1.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libpng=1.6.39
  - libpq=12.17
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nested_dict=1.61
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=3.0.13
  - packaging=22.0
  - pcre2=10.42
  - pillow=9.4.0
  - pip=22.3.1
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.7.1
  - python-dateutil=2.8.2
  - pytorch=1.8.0
  - pytorch-mutex=1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - scipy=1.7.3
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - toml=0.10.2
  - torchaudio=0.8.0
  - tornado=6.2
  - tqdm=4.64.1
  - typing_extensions=4.4.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - wincertstore=0.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
